project:
  type: site
  render:
    - "*.qmd"
    - "!poster.qmd"


site:
  title: "Prereg the Multiverse"
  navbar:
    type: dark
    background: light
    left:
      - href: index.qmd
        text: Home
      - preregistration-guide.qmd
      - preregistration-example.qmd
      - shiny-app.qmd
  repo-url: https://github.com/jflournoy/multiverse-preregistration
  repo-actions: issue

format:
  html:
    theme: simplex
    css: styles.css
    toc: true


